### ISSUE TITLE
Refactoring the code and arrange it in a logical order

### ISSUE THREAD

**Issue by aswarth123** [aswarth123/Java-project#1]
This work is assingned to @VisswanadhSai as he is already familiar with the source code of DDL commands. 

- [x]  Arrange the code in such a way that the the insert queries of each table are placed just below the DDL command of that table.
- [x]  Make sure that the tables having no foreign keys are created first and then the tables which are dependent on that particular  table.

Instructions:
1. Fork the repo and make your chnges first.
2. Verify your changes and if you find everyhting is fine then check the check boxes above and send a pull request.
3. Any furthur changes and clarifications will be reported to you by this thread.
4. Deadline December 4, 2020. Try to adhere to deadline as this will not take much time.

Note: For selecting the check box insert x in between the brackets like this --> [x].

Happy coding!

**Comment by VisswanadhSai** [comment]
Okay

**Comment by aswarth123** [comment]
You can also document the description of data that you have written on paper. We can add that to this repo so that others understand the short forms of the data which you used.
